---
- name: "Updating the guest operating system."
  ansible.builtin.apt:
    force_apt_get: true
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"
- name: "Installing additional packages."
  ansible.builtin.apt:
    name:
      - acl
      - apt-transport-https
      - bash-completion
      - ca-certificates
      - dnsutils
      - curl
      - git
      - gnupg
      - iperf3
      - jq
      - lvm2
      - net-tools
      - netcat-openbsd
      - nfs-common
      - python3
      - python3-pip
      - python-is-python3
      - python3-csvkit
      - python3-boto3
      - python3-full
      - unzip
      - wget
    state: latest     # noqa package-latest
