---
- name: "Updating the guest operating system."
  ansible.builtin.apt:
    force_apt_get: true
    name: "*"
    state: latest     # noqa package-latest
    update_cache: "yes"

- name: "Installing additional packages."
  ansible.builtin.apt:
    name:
      - acl
      - bash-completion
      - ca-certificates
      - curl
      - git
      - gnupg
      - lvm2
      - net-tools
      - netcat-openbsd
      - nfs-common
      - python3
      - python3-csvkit
      - python3-pip
      - python-is-python3
      - unzip
      - wget
    state: latest     # noqa package-latest
