---
name: "Code Quality"
on:
  push:
  pull_request:
jobs:
  superlinter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - name: Lint Code
        uses: github/super-linter@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # v7
        env:
          GITHUB_TOKEN: ${{ github.token }}
          FILTER_REGEX_EXCLUDE: "build.tmpl"
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          VALIDATE_ANSIBLE: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_MARKDOWN: false
