---
name: "Code Quality"
on:
  push:
  pull_request:
jobs:
  superlinter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@43045ae669be728bd34ed56fcd1a230c0dc4d8e2 # v4.0.0
        with:
          fetch-depth: 0
      - name: Lint Code
        uses: github/super-linter@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          FILTER_REGEX_EXCLUDE: "build.tmpl"
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          VALIDATE_ANSIBLE: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_MARKDOWN: false
